### ISSUE TITLE
Compiler

### ISSUE THREAD

**Issue by TacTicTow** [bradstv/exo-movement-mod#1]
Sorry, I did not see another way to get in touch with you. 

How were you able to compile a mod for H1? I cannot find anything anywhere to do this. I compiled the most recent release of zonetool, but have not even figured out how to dump all the load screen images. There is so very little documentation for modding H1. I am impressed you were able to do so!

**Comment by bradstv** [comment]
Not an issue related to the mod, you can find help in the H1-Mod (Aurora) [discord](https://discord.com/invite/RzzXu5EVnh)
